In [1]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv("/content/german.data",sep=r"\s+",header=None)

In [22]:
print(df.head())

    0   1    2    3     4    5    6   7    8     9   ...    11  12    13  \
0  A11   6  A34  A43  1169  A65  A75   4  A93  A101  ...  A121  67  A143
1  A12  48  A32  A43  5951  A61  A73   2  A92  A101  ...  A121  22  A143
2  A14  12  A34  A46  2096  A61  A74   2  A93  A101  ...  A121  49  A143
3  A11  42  A32  A42  7882  A61  A74   2  A93  A103  ...  A122  45  A143
4  A11  24  A33  A40  4870  A61  A73   3  A93  A101  ...  A124  53  A143

     14 15    16 17    18    19 20
0  A152  2  A173  1  A192  A201  1
1  A152  1  A173  1  A191  A201  2
2  A152  1  A172  2  A191  A201  1
3  A153  1  A173  2  A191  A201  1
4  A153  2  A173  2  A191  A201  2

[5 rows x 21 columns]

In [23]:
df.head

<bound method NDFrame.head of       0   1    2    3     4    5    6   7    8     9   ...    11  12    13  \
0    A11   6  A34  A43  1169  A65  A75   4  A93  A101  ...  A121  67  A143
1    A12  48  A32  A43  5951  A61  A73   2  A92  A101  ...  A121  22  A143
2    A14  12  A34  A46  2096  A61  A74   2  A93  A101  ...  A121  49  A143
3    A11  42  A32  A42  7882  A61  A74   2  A93  A103  ...  A122  45  A143
4    A11  24  A33  A40  4870  A61  A73   3  A93  A101  ...  A124  53  A143
..   ...  ..  ...  ...   ...  ...  ...  ..  ...   ...  ...   ...  ..   ...
995  A14  12  A32  A42  1736  A61  A74   3  A92  A101  ...  A121  31  A143
996  A11  30  A32  A41  3857  A61  A73   4  A91  A101  ...  A122  40  A143
997  A14  12  A32  A43   804  A61  A75   4  A93  A101  ...  A123  38  A143
998  A11  45  A32  A43  1845  A61  A73   4  A93  A101  ...  A124  23  A143
999  A12  45  A34  A41  4576  A62  A71   3  A93  A101  ...  A123  27  A143

       14 15    16 17    18    19 20
0    A152  2  A173  1  A192  A201  1
1    A152  1  A173  1  A191  A201  2
2    A152  1  A172  2  A191  A201  1
3    A153  1  A173  2  A191  A201  1
4    A153  2  A173  2  A191  A201  2
..    ... ..   ... ..   ...   ... ..
995  A152  1  A172  1  A191  A201  1
996  A152  1  A174  1  A192  A201  1
997  A152  1  A173  1  A191  A201  1
998  A153  1  A173  1  A192  A201  2
999  A152  1  A173  1  A191  A201  1

[1000 rows x 21 columns]>

In [24]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

In [6]:
print("Dataset Shape: ",df.shape)

Dataset Shape:  (1000, 21)

In [7]:
print(df.head())

    0   1    2    3     4    5    6   7    8     9   ...    11  12    13  \
0  A11   6  A34  A43  1169  A65  A75   4  A93  A101  ...  A121  67  A143
1  A12  48  A32  A43  5951  A61  A73   2  A92  A101  ...  A121  22  A143
2  A14  12  A34  A46  2096  A61  A74   2  A93  A101  ...  A121  49  A143
3  A11  42  A32  A42  7882  A61  A74   2  A93  A103  ...  A122  45  A143
4  A11  24  A33  A40  4870  A61  A73   3  A93  A101  ...  A124  53  A143

     14 15    16 17    18    19 20
0  A152  2  A173  1  A192  A201  1
1  A152  1  A173  1  A191  A201  2
2  A152  1  A172  2  A191  A201  1
3  A153  1  A173  2  A191  A201  1
4  A153  2  A173  2  A191  A201  2

[5 rows x 21 columns]

In [8]:
columns = [
    "checking_status",
    "duration",
    "credit_history",
    "purpose",
    "credit_amount",
    "savings_status",
    "employment",
    "installment_rate",
    "personal_status_sex",
    "other_debtors",
    "residence_since",
    "property",
    "age",
    "other_installment_plans",
    "housing",
    "existing_credits",
    "job",
    "num_dependents",
    "telephone",
    "foreign_worker",
    "target"
]

df.columns = columns

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (1000, 21)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_rate,personal_status_sex,other_debtors,...,property,age,other_installment_plans,housing,existing_credits,job,num_dependents,telephone,foreign_worker,target
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

In [9]:
print(df["target"].value_counts())

target
1    700
2    300
Name: count, dtype: int64

In [10]:
print("Data types: ")
print(df.dtypes)

Data types:
checking_status            object
duration                    int64
credit_history             object
purpose                    object
credit_amount               int64
savings_status             object
employment                 object
installment_rate            int64
personal_status_sex        object
other_debtors              object
residence_since             int64
property                   object
age                         int64
other_installment_plans    object
housing                    object
existing_credits            int64
job                        object
num_dependents              int64
telephone                  object
foreign_worker             object
target                      int64
dtype: object

In [11]:
print("Missing Values per column: ")
print(df.isnull().sum())

Missing Values per column:
checking_status            0
duration                   0
credit_history             0
purpose                    0
credit_amount              0
savings_status             0
employment                 0
installment_rate           0
personal_status_sex        0
other_debtors              0
residence_since            0
property                   0
age                        0
other_installment_plans    0
housing                    0
existing_credits           0
job                        0
num_dependents             0
telephone                  0
foreign_worker             0
target                     0
dtype: int64

In [12]:
print("Duplicate rows: ",df.duplicated().sum())

Duplicate rows:  0

In [14]:

print("Target distribution:")
print(df["target"].value_counts())

print("\nTarget distribution in percentage:")
print(df["target"].value_counts(normalize=True) * 100)

Target distribution:
target
1    700
2    300
Name: count, dtype: int64

Target distribution in percentage:
target
1    70.0
2    30.0
Name: proportion, dtype: float64

In [15]:

print("Dataset shape:", df.shape)

print("\nTarget distribution:")
print(df["target"].value_counts())

print("\nColumn names:")
print(df.columns.tolist())

Dataset shape: (1000, 21)

Target distribution:
target
1    700
2    300
Name: count, dtype: int64

Column names:
['checking_status', 'duration', 'credit_history', 'purpose', 'credit_amount', 'savings_status', 'employment', 'installment_rate', 'personal_status_sex', 'other_debtors', 'residence_since', 'property', 'age', 'other_installment_plans', 'housing', 'existing_credits', 'job', 'num_dependents', 'telephone', 'foreign_worker', 'target']